server:
  port: 8080
spring:
  application:
    name: pet
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pet
    username: root
    password: '010519'
    hikari:
      minimum-idle: 1
  mvc:
    servlet:
      load-on-startup: 1
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
knife4j:
  enable: true
  setting:
    language: zh_cn