server:
  port: 8080
spring:
  application:
    name: pet
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pet
    username: root
    password: '010519'
    hikari:
      minimum-idle: 1
  mvc:
    servlet:
      load-on-startup: 1
  redis:
    host: 127.0.0.1
    port: 6379
    password: '010519'
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
knife4j:
  enable: true
  setting:
    language: zh_cn
sa-token:
  token-name: token
dromara:
  x-file-storage:
    default-platform: qiniu-kodo-1
    thumbnail-suffix: ".jpg"
    qiniu-kodo:
      - platform: qiniu-kodo-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: C1AmRfZvtZqa_BaSMR5ikU5U91dcoGMgwmo2GT-9
        secret-key: te0QflMqdDaiWDrpS5nFdwmvu6YILEBGVpRZMBcS
        bucket-name: zzs-pet
        domain: http://sdy0ifgam.hn-bkt.clouddn.com/
        base-path: pic/ # 基础路径